#ifndef GLOBALS_HPP
#define GLOBALS_HPP

#define CELL_SIZE 100
#define CELL_DRAW_OFFSET 4
#define GRID_WIDTH 7
#define GRID_HEIGHT 6

#define BACKGROUND_COLOR 0x505859FF // #505859
#define EMPTY_CELL_COLOR 0xFFFFFFFF // #FFFFFF
#define RED_CELL_COLOR 0xC0392BFF	// #C0392B
#define YELLOW_CELL_COLOR 0xF1C40FFF// #F1C40FFF

#define WINDOW_WIDTH (CELL_SIZE * GRID_WIDTH + CELL_DRAW_OFFSET * (GRID_WIDTH + 1))
#define WINDOW_HEIGHT (CELL_SIZE * GRID_HEIGHT + CELL_DRAW_OFFSET * (GRID_HEIGHT + 1))

#endif
